### ISSUE TITLE
omniauth shibboleth issue

### ISSUE THREAD

**Issue by harshadsawant** [toyokazu/omniauth-shibboleth#25]
Started POST "/users/auth/shibboleth" for 202.52.53.201 at 2022-03-07 17:09:23 +0530
Processing by Gitlab::RequestForgeryProtection::Controller#index as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 149)
Started GET "/-/metrics" for 127.0.0.1 at 2022-03-07 17:09:27 +0530
Processing by MetricsController#index as HTML
Completed 200 OK in 80ms (Views: 0.6ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 1203)
Started GET "/api/v4/geo/proxy" for 127.0.0.1 at 2022-03-07 17:09:28 +0530
Started GET "/users/auth/shibboleth/callback" for 202.52.53.233 at 2022-03-07 17:09:29 +0530
  
**NoMethodError (undefined method `gsub' for nil:NilClass):**
  
lib/gitlab/metrics/elasticsearch_rack_middleware.rb:16:in `call'
lib/gitlab/middleware/rails_queue_duration.rb:33:in `call'
lib/gitlab/middleware/memory_report.rb:13:in `call'
lib/gitlab/middleware/speedscope.rb:13:in `call'
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/database/load_balancing/rack_middleware.rb:23:in `call'
lib/gitlab/metrics/rack_middleware.rb:16:in `block in call'
lib/gitlab/metrics/web_transaction.rb:46:in `run'
lib/gitlab/metrics/rack_middleware.rb:16:in `call'
lib/gitlab/jira/middleware.rb:19:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:21:in `call'
lib/gitlab/middleware/multipart.rb:173:in `call'
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'

when we going to shobboleth after entered username password then signed in confirm page then gitlab not redirecting happen.
Please tell us How to resolved this problem.
Please anyone help us..
ASAP.

**Comment by alansill** [comment]
See https://gitlab.com/gitlab-org/gitlab/-/issues/393065 -- apparently GitLab has deprecated and removed support for this gem until it can be vendored and updated. Intervention from the maintainers of from community input will be required to solve the associated issues.
